Item_list = ('Baby Acara Morphing Potion', 'Checkered Acara Morphing Potion', 'Christmas Acara Morphing Potion',
             'Cloud Acara Morphing Potion', 'Darigan Acara Morphing Potion', 'Disco Acara Morphing Potion',
             'Faerie Acara Morphing Potion', 'Fire Acara Morphing Potion', 'Ghost Acara Morphing Potion',
             'Green Acara Morphing Potion', 'Island Acara Morphing Potion', 'Maraquan Acara Morphing Potion',
             'Water Acara Morphing Potion', 'Woodland Acara Morphing Potion', 'Baby Aisha Morphing Potion',
             'Blue Aisha Morphing Potion', 'Brown Aisha Morphing Potion', 'Checkered Aisha Morphing Potion',
             'Christmas Aisha Morphing Potion', 'Clay Aisha Morphing Potion', 'Darigan Aisha Morphing Potion',
             'Desert Aisha Morphing Potion', 'Dimensional Aisha Morphing Potion', 'Eventide Aisha Morphing Potion',
             'Faerie Aisha Morphing Potion', 'Fire Aisha Morphing Potion', 'Green Aisha Morphing Potion',
             'Halloween Aisha Morphing Potion', 'Island Aisha Morphing Potion', 'Maractite Aisha Morphing Potion',
             'Pirate Aisha Morphing Potion', 'Plushie Aisha Morphing Potion', 'Purple Aisha Morphing Potion',
             'Rainbow Aisha Morphing Potion', 'Red Aisha Morphing Potion', 'Snow Aisha Morphing Potion',
             'Striped Aisha Morphing Potion', 'Yellow Aisha Morphing Potion', 'Zombie Aisha Morphing Potion',
             'Blue Bori Morphing Potion', 'Checkered Bori Morphing Potion', 'Christmas Bori Morphing Potion',
             'Cloud Bori Morphing Potion', 'Darigan Bori Morphing Potion', 'Faerie Bori Morphing Potion',
             'Fire Bori Morphing Potion', 'Green Bori Morphing Potion', 'Halloween Bori Morphing Potion',
             'Island Bori Morphing Potion', 'Pirate Bori Morphing Potion', 'Plushie Bori Morphing Potion',
             'Rainbow Bori Morphing Potion', 'Red Bori Morphing Potion', 'Snow Bori Morphing Potion',
             'Speckled Bori Morphing Potion', 'Spotted Bori Morphing Potion', 'Starry Bori Morphing Potion',
             'Tyrannian Bori Morphing Potion', 'Woodland Bori Morphing Potion', 'Yellow Bori Morphing Potion',
             'Baby Bruce Morphing Potion', 'Blue Bruce Morphing Potion', 'Brown Bruce Morphing Potion',
             'Christmas Bruce Morphing Potion', 'Cloud Bruce Morphing Potion', 'Disco Bruce Morphing Potion',
             'Faerie Bruce Morphing Potion', 'Fire Bruce Morphing Potion', 'Green Bruce Morphing Potion',
             'Island Bruce Morphing Potion', 'Plushie Bruce Morphing Potion', 'Red Bruce Morphing Potion',
             'Snow Bruce Morphing Potion', 'Speckled Bruce Morphing Potion', 'Split Bruce Morphing Potion',
             'Starry Bruce Morphing Potion', 'Strawberry Bruce Morphing Potion', 'Wraith Bruce Morphing Potion',
             'Yellow Bruce Morphing Potion', 'Baby Chomby Morphing Potion', 'Blue Chomby Morphing Potion',
             'Christmas Chomby Morphing Potion', 'Disco Chomby Morphing Potion', 'Fire Chomby Morphing Potion',
             'Green Chomby Morphing Potion', 'Island Chomby Morphing Potion', 'Pirate Chomby Morphing Potion',
             'Plushie Chomby Morphing Potion', 'Rainbow Chomby Morphing Potion', 'Red Chomby Morphing Potion',
             'Shadow Chomby Morphing Potion', 'White Chomby Morphing Potion', 'Yellow Chomby Morphing Potion',
             'Blue Cybunny Morphing Potion', 'Camouflage Cybunny Morphing Potion', 'Christmas Cybunny Morphing Potion',
             'Cloud Cybunny Morphing Potion', 'Faerie Cybunny Morphing Potion', 'Green Cybunny Morphing Potion',
             'Grey Cybunny Morphing Potion', 'Halloween Cybunny Morphing Potion', 'Island Cybunny Morphing Potion',
             'Maraquan Cybunny Morphing Potion', 'Pirate Cybunny Morphing Potion', 'Plushie Cybunny Morphing Potion',
             'Rainbow Cybunny Morphing Potion', 'Red Cybunny Morphing Potion', 'Shadow Cybunny Morphing Potion',
             'Speckled Cybunny Morphing Potion', 'Starry Cybunny Morphing Potion', 'Woodland Cybunny Morphing Potion',
             'Yellow Cybunny Morphing Potion', 'Zombie Cybunny Morphing Potion', 'Blue Draik Morphing Potion',
             'Darigan Draik Morphing Potion', 'Eventide Draik Morphing Potion', 'Faerie Draik Morphing Potion',
             'Fire Draik Morphing Potion', 'Ghost Draik Morphing Potion', 'Green Draik Morphing Potion',
             'Grey Draik Morphing Potion', 'Maractite Draik Morphing Potion', 'Pink Draik Morphing Potion',
             'Pirate Draik Morphing Potion', 'Plushie Draik Morphing Potion', 'Purple Draik Morphing Potion',
             'Red Draik Morphing Potion', 'Skunk Draik Morphing Potion', 'Starry Draik Morphing Potion',
             'Water Draik Morphing Potion', 'Woodland Draik Morphing Potion', 'Wraith Draik Morphing Potion',
             'Yellow Draik Morphing Potion', 'Blue Eyrie Morphing Potion', 'Cloud Eyrie Morphing Potion',
             'Darigan Eyrie Morphing Potion', 'Faerie Eyrie Morphing Potion', 'Green Eyrie Morphing Potion',
             'Halloween Eyrie Morphing Potion', 'Island Eyrie Morphing Potion', 'Pink Eyrie Morphing Potion',
             'Pirate Eyrie Morphing Potion', 'Purple Eyrie Morphing Potion', 'Red Eyrie Morphing Potion',
             'Skunk Eyrie Morphing Potion', 'Snow Eyrie Morphing Potion', 'Spotted Eyrie Morphing Potion',
             'Starry Eyrie Morphing Potion', 'Tyrannian Eyrie Morphing Potion', 'Yellow Eyrie Morphing Potion',
             'Zombie Eyrie Morphing Potion', 'Blue Flotsam Morphing Potion', 'Desert Flotsam Morphing Potion',
             'Faerie Flotsam Morphing Potion', 'Fire Flotsam Morphing Potion', 'Green Flotsam Morphing Potion',
             'Pirate Flotsam Morphing Potion', 'Plushie Flotsam Morphing Potion', 'Rainbow Flotsam Morphing Potion',
             'Red Flotsam Morphing Potion', 'Skunk Flotsam Morphing Potion', 'Snow Flotsam Morphing Potion',
             'Split Flotsam Morphing Potion', 'Spotted Flotsam Morphing Potion', 'Starry Flotsam Morphing Potion',
             'Striped Flotsam Morphing Potion', 'Tyrannian Flotsam Morphing Potion', 'Water Flotsam Morphing Potion',
             'White Flotsam Morphing Potion', 'Yellow Flotsam Morphing Potion', 'Zombie Flotsam Morphing Potion',
             'Blue Gelert Morphing Potion', 'Christmas Gelert Morphing Potion', 'Cloud Gelert Morphing Potion',
             'Eventide Gelert Morphing Potion', 'Ghost Gelert Morphing Potion', 'Green Gelert Morphing Potion',
             'Island Gelert Morphing Potion', 'Maraquan Gelert Morphing Potion', 'Red Gelert Morphing Potion',
             'Spotted Gelert Morphing Potion', 'Wraith Gelert Morphing Potion', 'Yellow Gelert Morphing Potion',
             'Baby Grundo Morphing Potion', 'Blue Grundo Morphing Potion', 'Brown Grundo Morphing Potion',
             'Christmas Grundo Morphing Potion', 'Cloud Grundo Morphing Potion', 'Darigan Grundo Morphing Potion',
             'Desert Grundo Morphing Potion', 'Faerie Grundo Morphing Potion', 'Green Grundo Morphing Potion',
             'Halloween Grundo Morphing Potion', 'Island Grundo Morphing Potion', 'Pirate Grundo Morphing Potion',
             'Plushie Grundo Morphing Potion', 'Purple Grundo Morphing Potion', 'Rainbow Grundo Morphing Potion',
             'Spotted Grundo Morphing Potion', 'Starry Grundo Morphing Potion', 'Woodland Grundo Morphing Potion',
             'Wraith Grundo Morphing Potion', 'Yellow Grundo Morphing Potion', 'Baby Hissi Morphing Potion',
             'Blue Hissi Morphing Potion', 'Desert Hissi Morphing Potion', 'Eventide Hissi Morphing Potion',
             'Faerie Hissi Morphing Potion', 'Ghost Hissi Morphing Potion', 'Green Hissi Morphing Potion',
             'Halloween Hissi Morphing Potion', 'Island Hissi Morphing Potion', 'Maractite Hissi Morphing Potion',
             'Maraquan Hissi Morphing Potion', 'Pirate Hissi Morphing Potion', 'Plushie Hissi Morphing Potion',
             'Rainbow Hissi Morphing Potion', 'Red Hissi Morphing Potion', 'Shadow Hissi Morphing Potion',
             'Spotted Hissi Morphing Potion', 'Starry Hissi Morphing Potion', 'Yellow Hissi Morphing Potion',
             'Blue Ixi Morphing Potion', 'Brown Ixi Morphing Potion', 'Christmas Ixi Morphing Potion',
             'Cloud Ixi Morphing Potion', 'Darigan Ixi Morphing Potion', 'Desert Ixi Morphing Potion',
             'Electric Ixi Morphing Potion', 'Eventide Ixi Morphing Potion', 'Faerie Ixi Morphing Potion',
             'Fire Ixi Morphing Potion', 'Green Ixi Morphing Potion', 'Grey Ixi Morphing Potion',
             'Halloween Ixi Morphing Potion', 'Island Ixi Morphing Potion', 'Maraquan Ixi Morphing Potion',
             'Pirate Ixi Morphing Potion', 'Plushie Ixi Morphing Potion', 'Red Ixi Morphing Potion',
             'Shadow Ixi Morphing Potion', 'Striped Ixi Morphing Potion', 'Tyrannian Ixi Morphing Potion',
             'White Ixi Morphing Potion', 'Yellow Ixi Morphing Potion', 'Baby Jetsam Morphing Potion',
             'Blue Jetsam Morphing Potion', 'Dimensional Jetsam Morphing Potion', 'Glowing Jetsam Morphing Potion',
             'Green Jetsam Morphing Potion', 'Plushie Jetsam Morphing Potion', 'Red Jetsam Morphing Potion',
             'Spotted Jetsam Morphing Potion', 'Striped Jetsam Morphing Potion', 'Yellow Jetsam Morphing Potion',
             'Baby Kacheek Morphing Potion', 'Blue Kacheek Morphing Potion', 'Christmas Kacheek Morphing Potion',
             'Disco Kacheek Morphing Potion', 'Fire Kacheek Morphing Potion', 'Green Kacheek Morphing Potion',
             'Island Kacheek Morphing Potion', 'Maraquan Kacheek Morphing Potion', 'Pirate Kacheek Morphing Potion',
             'Rainbow Kacheek Morphing Potion', 'Red Kacheek Morphing Potion', 'Starry Kacheek Morphing Potion',
             'Strawberry Kacheek Morphing Potion', 'Yellow Kacheek Morphing Potion', 'Baby Kau Morphing Potion',
             'Blue Kau Morphing Potion', 'Darigan Kau Morphing Potion', 'Faerie Kau Morphing Potion',
             'Fire Kau Morphing Potion', 'Green Kau Morphing Potion', 'Halloween Kau Morphing Potion',
             'Plushie Kau Morphing Potion', 'Rainbow Kau Morphing Potion', 'Red Kau Morphing Potion',
             'Speckled Kau Morphing Potion', 'Spotted Kau Morphing Potion', 'Starry Kau Morphing Potion',
             'Striped Kau Morphing Potion', 'Water Kau Morphing Potion', 'Yellow Kau Morphing Potion',
             'Plushie Kougra Morphing Potion', 'Plushie Kougra Morphing Potion', 'Eventide Kougra Morphing Potion',
             'Dimensional Kougra Morphing Potion', 'Baby Kougra Morphing Potion', 'Blue Krawk Morphing Potion',
             'Camouflage Krawk Morphing Potion', 'Desert Krawk Morphing Potion', 'Faerie Krawk Morphing Potion',
             'Green Krawk Morphing Potion', 'Island Krawk Morphing Potion', 'Maractite Krawk Morphing Potion',
             'Maraquan Krawk Morphing Potion', 'Pirate Krawk Morphing Potion', 'Red Krawk Morphing Potion',
             'Stealthy Krawk Morphing Potion', 'Wraith Krawk Morphing Potion', 'Yellow Krawk Morphing Potion',
             'Faerie Lupe Morphing Potion', 'Fire Lupe Morphing Potion', 'Glowing Lupe Morphing Potion',
             'Green Lupe Morphing Potion', 'Island Lupe Morphing Potion', 'Rainbow Lupe Morphing Potion',
             'Red Lupe Morphing Potion', 'Skunk Lupe Morphing Potion', 'Split Lupe Morphing Potion',
             'Spotted Lupe Morphing Potion', 'Strawberry Lupe Morphing Potion', 'Baby Lupe Morphing Potion',
             'Desert Lutari Morphing Potion', 'Faerie Lutari Morphing Potion', 'Green Lutari Morphing Potion',
             'Island Lutari Morphing Potion', 'Pink Lutari Morphing Potion', 'Pirate Lutari Morphing Potion',
             'Stealthy Lutari Morphing Potion', '8-bit Power-Up Potion', 'Baby Poogle Morphing Potion',
             'Blue Poogle Morphing Potion', 'Checkered Poogle Morphing Potion', 'Cloud Poogle Morphing Potion',
             'Desert Poogle Morphing Potion', 'Dimensional Poogle Morphing Potion', 'Eventide Poogle Morphing Potion',
             'Faerie Poogle Morphing Potion', 'Fire Poogle Morphing Potion', 'Glowing Poogle Morphing Potion',
             'Green Poogle Morphing Potion', 'Island Poogle Morphing Potion', 'Pirate Poogle Morphing Potion',
             'Plushie Poogle Morphing Potion', 'Purple Poogle Morphing Potion', 'Rainbow Poogle Morphing Potion',
             'Red Poogle Morphing Potion', 'Yellow Poogle Morphing Potion', 'Baby Shoyru Morphing Potion',
             'Blue Shoyru Morphing Potion', 'Checkered Shoyru Morphing Potion', 'Christmas Shoyru Morphing Potion',
             'Cloud Shoyru Morphing Potion', 'Dimensional Shoyru Morphing Potion', 'Disco Shoyru Morphing Potion',
             'Faerie Shoyru Morphing Potion', 'Fire Shoyru Morphing Potion', 'Ghost Shoyru Morphing Potion',
             'Gold Shoyru Morphing Potion', 'Green Shoyru Morphing Potion', 'Island Shoyru Morphing Potion',
             'Pink Shoyru Morphing Potion', 'Pirate Shoyru Morphing Potion', 'Purple Shoyru Morphing Potion',
             'Rainbow Shoyru Morphing Potion', 'Red Shoyru Morphing Potion', 'Shadow Shoyru Morphing Potion',
             'Silver Shoyru Morphing Potion', 'Speckled Shoyru Morphing Potion', 'Spotted Shoyru Morphing Potion',
             'Starry Shoyru Morphing Potion', 'Striped Shoyru Morphing Potion', 'White Shoyru Morphing Potion',
             'Wraith Shoyru Morphing Potion', 'Yellow Shoyru Morphing Potion', 'Baby Uni Morphing Potion',
             'Blue Uni Morphing Potion', 'Brown Uni Morphing Potion', 'Christmas Uni Morphing Potion',
             'Faerie Uni Morphing Potion', 'Green Uni Morphing Potion', 'Halloween Uni Morphing Potion',
             'Island Uni Morphing Potion', 'Pink Uni Morphing Potion', 'Purple Uni Morphing Potion',
             'Rainbow Uni Morphing Potion', 'Red Uni Morphing Potion', 'Shadow Uni Morphing Potion',
             'Starry Uni Morphing Potion', 'Woodland Uni Morphing Potion', 'Yellow Uni Morphing Potion',
             'Baby Usul Morphing Potion', 'Blue Usul Morphing Potion', 'Faerie Usul Morphing Potion',
             'Green Usul Morphing Potion', 'Island Usul Morphing Potion', 'Maraquan Usul Morphing Potion',
             'Pirate Usul Morphing Potion', 'Plushie Usul Morphing Potion', 'Red Usul Morphing Potion',
             'Snow Usul Morphing Potion', 'Starry Usul Morphing Potion', 'Tyrannian Usul Morphing Potion',
             'Water Usul Morphing Potion', 'Yellow Usul Morphing Potion', 'Zombie Usul Morphing Potion',
             'Blue Vandagyre Morphing Potion', 'Green Vandagyre Morphing Potion', 'Red Vandagyre Morphing Potion',
             'Yellow Vandagyre Morphing Potion', 'Blue Xweetok Morphing Potion', 'Faerie Xweetok Morphing Potion',
             'Fire Xweetok Morphing Potion', 'Green Xweetok Morphing Potion', 'Halloween Xweetok Morphing Potion',
             'Island Xweetok Morphing Potion', 'Pastel Xweetok Morphing Potion', 'Red Xweetok Morphing Potion',
             'Speckled Xweetok Morphing Potion', 'Starry Xweetok Morphing Potion', 'Striped Xweetok Morphing Potion',
             'White Xweetok Morphing Potion', 'Yellow Xweetok Morphing Potion', 'Blue Zafara Morphing Potion',
             'Christmas Zafara Morphing Potion', 'Darigan Zafara Morphing Potion', 'Eventide Zafara Morphing Potion',
             'Green Zafara Morphing Potion', 'Grey Zafara Morphing Potion', 'Island Zafara Morphing Potion',
             'Purple Zafara Morphing Potion', 'Red Zafara Morphing Potion', 'Starry Zafara Morphing Potion',
             'Yellow Zafara Morphing Potion')

item_list_2 = ("Potion of Concealment")
# run code cleanup

item_list = []
item_list_3 = ['Magical Pea Chia Pop', 'Angelic Ice Lolly', 'Hamarama Ice Lolly', 'Maractite Ice Lolly', 'Magical Asparagus Chia Pop',
               'Magical Grape Chia Pop', 'Magical Apple Chia Pop', 'Magical Peach Chia Pop', 'Magical Pear Chia Pop', 'Magical Gooseberry Chia Pop',
               'Magical Tomato Chia Pop', 'Magical Pepper Chia Pop', 'Magical Agueena Chia Pop', 'Magical Pineapple Chia Pop', 'Magical Avocado Chia Pop',
               'Magical Durian Chia Pop', 'Magical Ummagine Chia Pop', 'Magical Orange Chia Pop', 'Magical Thornberry Chia Pop', 'Magical Carrot Chia Pop',
               'Magical Chokato Chia Pop', 'Magical Lime Chia Pop', 'Magical Blueberry Chia Pop', 'Magical Aubergine Chia Pop', 'Magical Plum Chia Pop',
               'Magical Coconut Chia Pop', 'Magical Lemon Chia Pop', 'Magical Onion Chia Pop', 'Magical Strawberry Chia Pop', 'Magical Juppie Swirl Chia Pop']

